# Generated by Django 3.1.5 on 2021-02-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210228_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdashboard',
            name='invite_link',
            field=models.CharField(blank=True, default='', max_length=16),
            preserve_default=False,
        ),
    ]
