# Generated by Django 3.1.5 on 2021-03-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thoth_Gaming', '0005_auto_20210216_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('track_id', models.IntegerField()),
                ('id_number', models.CharField(max_length=100)),
                ('oder_id', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('card_number', models.CharField(max_length=200)),
                ('hash_card_number', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
