# Generated by Django 3.1.5 on 2021-01-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('rarities', models.CharField(choices=[('Legendary', 'Legendary'), ('Immortal', 'Immortal'), ('Arcana', 'Arcana'), ('Rare', 'Rare'), ('Common', 'Common'), ('Persona', 'Persona')], max_length=255)),
            ],
        ),
    ]
