# Generated by Django 3.1.5 on 2021-01-27 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Thoth_Gaming', '0001_initial'),
        ('items', '0002_items_picture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='items',
            new_name='item',
        ),
    ]
